name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  version-next:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version-next: ${{ steps.reference.outputs.next-reference }}
      version-next-strict: ${{ steps.reference.outputs.next-reference }}
    steps:
      - uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2

      - name: Next Reference
        id: reference
        uses: wearefrank/ci-cd-templates/next-reference@2bdd123ba53833578d6f63e3426c32e0c8e25d67 #2.2.7

  ci:
    uses: wearefrank/ci-cd-templates/.github/workflows/ci-generic.yml@2bdd123ba53833578d6f63e3426c32e0c8e25d67 #2.2.7
    needs:
      - version-next
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      version: ${{ needs.version-next.outputs.version-next }}
      run-frank-till-healthy-enabled: false

  larva:
    uses: wearefrank/ci-cd-templates/.github/workflows/larva-testrunner.yml@2824723a572674093bda421842da85b373aaf8a7 #2.4.0
    needs:
      - version-next
      - ci
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-staging@${{ needs.ci.outputs.image-digest }}
      setup-script: |
        docker run -d --name morcoreintegration -p 8080:8080 -e dtap.stage=LOC "${IMAGE_ID:-${IMAGE_REF}}"
      teardown-script: |
        docker stop "${CONTAINER_ID}"
        docker rm --volumes "${CONTAINER_ID}"
